name: 'Deploy to Cloud Hub 1.0'

inputs:
  clientId:
    required: true
  clientSecret:
    required: true
  environment:
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout this repo
      uses: actions/checkout@v4
  
    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
  
    - uses: actions/download-artifact@v4
      with:
        name: artifacts
  
    - name: Deploy the application
      run: |
        artifactName=$(ls *.jar | head -1)
        mvn deploy -DmuleDeploy -DskipMunitTests -PcloudHubDeployment\
         -Dmule.artifact=$artifactName \
         -Dclient.id="$clientId" \
         -Dclient.secret="$clientSecret" \
         -Danypoint.environment="$environment"
      shell: bash
      env:
        clientId: ${{ inputs.clientId }}
        clientSecret: ${{ inputs.clientSecret }}
        environment: ${{ inputs.environment }}