name: 'Deploy to Cloud Hub 2.0'

inputs:
  username:
    required: true
  password:
    required: true
  environment:
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout this repo
      uses: actions/checkout@v4
  
    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
  
    - uses: actions/download-artifact@v4
      with:
        name: artifacts

    - name: Publish to Exchange
      run: |
        mvn deploy --settings .maven/settings.xml -DskipMunitTests \
         -Danypoint.username="$username" \
         -Danypoint.password="$password" \
      shell: bash
      env:
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}

    - name: Deploy the application
      run: |
        artifactName=$(ls *.jar | head -1)
        mvn deploy --settings .maven/settings.xml -DmuleDeploy -DskipMunitTests -Pcloudhub2Deployment\
         -Dmule.artifact=$artifactName \
         -Danypoint.username="$username" \
         -Danypoint.password="$password" \
         -Danypoint.environment="$environment"
      shell: bash
      env:
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}
        environment: ${{ inputs.environment }}
    
    # - name: Read current application version
    #   id: read_version
    #   uses: wzieba/read-maven-pom-action@v1
    #   with:
    #     path: 'pom.xml'

    # - name: Print current application version
    #   run: echo "Current application version is ${{ steps.read_version.outputs.version }}"
    #   shell: bash

    - name: Read version pom.xml
      id: getVersion
      uses: smacdonald-parallelz/github-action-get-pom-version@v1.0.2
  
    - name: Print the version
      run: echo "The version we just got is ${{ steps.getVersion.outputs.version }}"