name: Deploy to Anypoint Platform

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      username:
        required: true
        type: string
      password:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Print inputs
        run: |
          echo "environment: ${{ inputs.environment }}"
          echo "username: ${{ inputs.username }}"

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - uses: actions/download-artifact@v4
        with:
          name: artifacts

      - name: Deploy to ${{ inputs.environment }} environment
        run: |
          artifactName=$(ls *.jar | head -1)
          mvn deploy -DmuleDeploy \
           -Dmule.artifact=$artifactName \
           -Danypoint.username="${{ inputs.username }}" \
           -Danypoint.password="${{ inputs.password }}" \
           -Danypoint.environment="${{ inputs.environment }}"
